version: 2

models:
  - name: somente_da_area
    description: "Filtragem de registros da pesquisa para remover cargos não relevantes para a análise."
    columns:
      - name: cargo
        description: "O cargo do respondente."
      - name: count_registros
        description: "Número de registros para cada cargo."

  - name: porcentagem_dos_cargos
    description: "Calcula a porcentagem de cada cargo com base nos dados filtrados."
    columns:
      - name: cargo
        description: "O cargo do respondente."
        tests:
          - not_null
          - unique
      - name: count_registros
        description: "Número de registros para cada cargo."
      - name: porcentagem
        description: "Porcentagem do total de registros para cada cargo."